Выполнена разметка страницы формы
htmlacademy-adaptive/908213-pink-22 pull request #3
Opened 2021-03-28 19:59 UTC by SergeyBistrov

2021-03-29 06:38 UTC, mouxez requested changes

2021-03-29 06:38 UTC, mouxez commented on source/form.html
>          <form class="contest__form" action="https://echo.htmlacademy.ru/" method="post">
нужно сделать валидацию вводимых значений полей формы. сейчас можно отправить 2342345245 в поле имя, что не правильно (в других полях тоже есть такие проблемы).
идеальная форма:
- не должна отправляться пустой
- должны быть ограничены по количеству символов поля
- должны быть ограничены по типу вводимых данных (текст, цифры и тп)
почитай про это тут:
https://developer.mozilla.org/ru/docs/Learn/Forms/Form_validation

2021-03-29 06:38 UTC, mouxez commented on source/form.html
>          <form class="contest__form" action="https://echo.htmlacademy.ru/" method="post">
<img width="889" alt="Screenshot 2021-03-29 at 09 10 16" src="https://user-images.githubusercontent.com/48134013/112793813-9e34e100-906e-11eb-9e96-fffdab695f6e.png">

2021-03-29 06:38 UTC, mouxez commented on source/catalog.html
> +              <p class="gallery__quote-text">Прыгать или нет? Напишите в<br> комментарии свой совет и<br> смотрите прямую трансляцию в<br> перископе, задавайте свои вопросы!</p>
существует большой спор по поводу использования br для переноса. я придерживаюсь мнения, что проще регулировать переносы с помощью ширины блока + неразрывные пробелы

2021-03-29 06:38 UTC, mouxez commented on source/catalog.html
> +              <p class="gallery__quote-text">Прыгать или нет? Напишите в<br> комментарии свой совет и<br> смотрите прямую трансляцию в<br> перископе, задавайте свои вопросы!</p>
ты можешь делать как удобно

2021-03-29 06:38 UTC, mouxez commented on source/catalog.html
> +              <button class="editor-item__button" type="button" title="Залить цветом">
тут есть доработки по бэм
напиши мне в телегу логику присвоения имен классам на строчках 141 и 142
нам нужно разобраться с этим вопросом
секция называется post
далее идёт 
ul class="post__list editor-list"
            li class="editor-list__item editor-item"
для чего используешь миксование при именовании?
нужно переосмыслить имена у всего блока editor

2021-03-29 07:23 UTC, SergeyBistrov commented on source/blank.html
>    </head>
ок, понял. blank делаю по привычке с прошлого курса, такой вариант мне по душе.

2021-03-29 07:30 UTC, SergeyBistrov commented on source/catalog.html
> +              <p class="gallery__quote-text">Прыгать или нет? Напишите в<br> комментарии свой совет и<br> смотрите прямую трансляцию в<br> перископе, задавайте свои вопросы!</p>
Я согласен с тем, что лучше переносы текста регулировать шириной блока, но именно в этом месте видно, что по макету переносы сделаны специально - по макету там нижняя строчка длиннее верхней, а это значит был насильный сделан перенос верхней.

2021-03-29 07:30 UTC, SergeyBistrov commented on source/catalog.html
> +              <p class="gallery__quote-text">Прыгать или нет? Напишите в<br> комментарии свой совет и<br> смотрите прямую трансляцию в<br> перископе, задавайте свои вопросы!</p>
ок, понятно.

2021-03-30 05:50 UTC, mouxez approved these changes

2021-03-30 05:50 UTC, merged